include_recipe 'chef_rvm::rvm'
include_recipe 'chef_rvm::rubies'
include_recipe 'chef_rvm::gemsets'
include_recipe 'chef_rvm::gems'
include_recipe 'chef_rvm::wrappers'
include_recipe 'chef_rvm::aliases'
