name 'chef_rvm'
maintainer 'R&R Innovation LLC'
maintainer_email 'work at murga.kiev.ua'
license 'Apache v2.0'
description 'Installs/Configures rvm'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '2.0.1'

recipe 'chef_rvm', 'Installs all'
recipe 'chef_rvm::rvm', 'Installs the rvm for users'
recipe 'chef_rvm::rubies', 'Installs rubies'
recipe 'chef_rvm::gems', 'Creates gemsets and install gems'
recipe 'chef_rvm::packages', 'General recipe. Installs dependencies for other recipes.'
recipe 'chef_rvm::wrappers', 'Create wrappers'
recipe 'chef_rvm::aliases', 'Create aliases'

supports 'ubuntu'
supports 'debian'

depends 'sudo'
depends 'apt'
depends 'build-essential'
depends 'chef_gem'
depends 'curl'
depends 'aws', '~> 7.2.2'
depends 'ark', '~> 3.1.0'
